### ISSUE TITLE
Voxelization for 3D CNN

### ISSUE THREAD

**Issue by OneManArmy93** [fschaeffler93/best_voxelnet_ever#2]
Hello, im trying to impelemnt a singlestage detector (perception and prediction) which is inspired from IntenNet and Fast and Furious.
These two approaches uses voxelization to create a 3D voxel grid from point cloud data and feed it to a 3D CNN.
My question is, can i get inspired by the voxelization process in voxelnet to do the same?
Thank you

**Comment by fschaeffler93** [comment]
Hello,
I don't know how the voxelization has to be done in these approaches, but I think it should be very similar.
Take a look at the process_pointcloud function in utils/preprocess.py.
